services:
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Belgrade
      # OVO DODAJ: Govori ugrađenom web serveru da ne forsira HTTPS u lokalu
      - KASM_DISABLE_AUTH=1
    volumes:
      - /mnt/hdd/books:/config
    ports:
      - 4041:8080
    restart: unless-stopped
