---
services:
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Belgrade
    volumes:
      - /mnt/hdd/books:/config
    ports:
      - 4041:8080
    restart: unless-stopped
